= java-mavenmixin-staticanalysis
:_imagesdir: ./
:toc:


This module provides a link:https://github.com/odavid/maven-plugins[maven mixin] that can be incorporated into Maven module, configuring the link:https://maven.apache.org/plugins/maven-checkstyle-plugin/[checkstyle], link:https://maven.apache.org/plugins/maven-pmd-plugin/[pmd], link:http://www.mojohaus.org/javancss-maven-plugin/report-mojo.html[javancss] and link:http://gleclaire.github.io/findbugs-maven-plugin/[findbugs] plugins.
This reduces the size of the maven `pom.xml` file for that consuming module; it simply needs to reference _this_ module using the `mixin-maven-plugin`.

The appropriate configuration are included in a `<profile>`.
Because the plugins may takes a while to run, this profile is automatically disabled in all builds.
It can be enabled using a Maven property.

[NOTE]
====
This module was initially developed for use within link:http://isis.apache.org[Apache Isis] applications but can be used by any Java application.
====




== How to Configure

To configure:

* copy and paste the following into either the `pom.xml` of the consuming module or (better still) the `pom.xml` of the top-level parent of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <mavenmixin-staticanalysis.version>0.0.2</mavenmixin-staticanalysis.version>

    <maven-checkstyle-plugin.version>2.11</maven-checkstyle-plugin.version>
    <maven-pmd-plugin.version>3.0.1</maven-pmd-plugin.version>
    <javancss-maven-plugin.version>2.1</javancss-maven-plugin.version>
    <jdepend-maven-plugin.version>2.0-beta-2</jdepend-maven-plugin.version>
    <findbugs-maven-plugin.version>2.5</findbugs-maven-plugin.version>
    ...
</properties>
----
+
and: +
+
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${maven-pmd-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>javancss-maven-plugin</artifactId>
                <version>${javancss-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jdepend-maven-plugin</artifactId>
                <version>${jdepend-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>${findbugs-maven-plugin.version}</version>
            </plugin>
            ...
        </plugins>
    </pluginManagement>
</build>
----


* update the following property/ies in the `pom.xml` of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <maven-checkstyle-plugin.configLocation>checkstyle.xml</maven-checkstyle-plugin.configLocation>     <!--1-->
    <maven-pmd-plugin.ruleset>pmd.xml</maven-pmd-plugin.ruleset>                                        <!--2-->
    ...
</properties>
----
<1> the location of the link:https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html[checkstyle.xml] file
<2> the location of the link:https://maven.apache.org/plugins/maven-pmd-plugin/examples/usingRuleSets.html[pmd.xml] ruleset file

* add the following to the `pom.xml` of the consuming module: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    <mixin>
                        <groupId>com.danhaywood.mavenmixin</groupId>
                        <artifactId>staticanalysis</artifactId>
                        <version>${mavenmixin-staticanalysis.version}</version>
                    </mixin>
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----



== How to Use:

Although all of these plugins provide various "check" goals that can be bound to the build lifecycle, this mixin does _not_ set up any such `<execution>` bindings.
If required, set these up in the usual way within the `pom.xml` of the consuming module.

However, the plugin _does_ allow reports to be generated using the site lifecycle:

[source,bash]
----
mvn clean site -Dmavenmixin-staticanalysis
----

This will generate HTML website in the usual `target/site` directory.



== Known issues

None currently



== Change Log

* `0.0.2` - updates README for properties and plugin management, shortens property names and profile id
* `0.0.1` - first release




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----



=== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.2 \
              0.0.3-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
git push origin 0.0.2
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
